### ISSUE TITLE
Problem with brackets on gitignore patter

### ISSUE THREAD

**Issue by mhalano** [highb/pathspec-ruby#34]
I have a test on my pipeline for the gitignore file using the pathspec-ruby. Worked well with 0.2.1 but crashed with 1.0.0.
The error is this:
```
$ bundle exec rake syntax
rake aborted!
SyntaxError: /usr/local/bundle/gems/pathspec-1.0.0/lib/pathspec/gitignorespec.rb:45: syntax error, unexpected ']'
...         pattern = pattern[1..]
...                              ^
/usr/local/bundle/gems/pathspec-1.0.0/lib/pathspec/gitignorespec.rb:52: syntax error, unexpected ']'
        pattern = pattern[1..] if pattern.start_with?('\\')
                             ^
/usr/local/bundle/gems/pathspec-1.0.0/lib/pathspec.rb:1:in `require'
/usr/local/bundle/gems/pathspec-1.0.0/lib/pathspec.rb:1:in `<top (required)>'
/usr/local/bundle/gems/puppetlabs_spec_helper-2.16.0/lib/puppetlabs_spec_helper/tasks/check_symlinks.rb:3:in `require'
/usr/local/bundle/gems/puppetlabs_spec_helper-2.16.0/lib/puppetlabs_spec_helper/tasks/check_symlinks.rb:3:in `<top (required)>'
/usr/local/bundle/gems/puppetlabs_spec_helper-2.16.0/lib/puppetlabs_spec_helper/rake_tasks.rb:11:in `require'
/usr/local/bundle/gems/puppetlabs_spec_helper-2.16.0/lib/puppetlabs_spec_helper/rake_tasks.rb:11:in `<top (required)>'
/builds/equinix-mse/control-repo/Rakefile:1:in `require'
/builds/equinix-mse/control-repo/Rakefile:1:in `<top (required)>'
/usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```
The only line with brackets on the gitignore is `.*.sw[op]`

**Comment by highb** [comment]
@mhalano Thanks for the report! What Ruby version are you using?

**Comment by highb** [comment]
I suspect that you are using a version of Ruby before 2.6 because [endless ranges were introduced in that version](https://www.rubyguides.com/2018/11/ruby-2-6-new-features/). Could you attempt upgrading your Ruby version to 2.6 and see if that resolves the issue?

**Comment by highb** [comment]
@mhalano Is this still an issue for you?

**Comment by mhalano** [comment]
I couldn't say. I left the job where I used that. You may close the issue if you will.
